apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: example-host.com
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: docker-imagetragick-svc
                port: 
                  number: 80
            path: /
