apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagetragick
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagetragick
  template:
    metadata:
      labels:
        app: imagetragick
    spec:
      hostPID: true
      containers:
      - name: imagetragick
        image: craighurley/docker-imagetragick
        ports:
        - containerPort: 8080
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - SYS_ADMIN
---
apiVersion: v1
kind: Service
metadata:
  name: imagetragick
spec:
  selector:
    app: imagetragick
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
