---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: imagetragick
spec:
  ingressClassName: nginx
  rules:
  - host: imagetragick.cs.padok.school
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: imagetragick
            port:
              number: 8080
