---
# Default values: https://github.com/jetstack/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml
cert-manager:
  installCRDs: true

  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 1000m
      memory: 64Mi
