# Default values are available here: https://github.com/bitnami/charts/blob/master/bitnami/external-dns/values.yaml

external-dns:
  provider: aws
  namespace: external-dns
  policy: sync
  sources:
    - ingress
    - service
  registry: txt
  txtOwnerId: Z094281539ZLL7IUQZGF2
  serviceAccount:
    annotations:
      # ⚠️ Change this 👇
      eks.amazonaws.com/role-arn: arn:aws:iam::969990446292:role/external-dns
