apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: argocd
    name: in-cluster
  source:
    repoURL: git@github.com:padok-team/kubesecu-lab-cours.git
    path: ./argocd-config/applications/
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
